apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: offers-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "api.offers.dynolab.app"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: offers
spec:
  hosts:
  - "api.offers.dynolab.app"
  gateways:
  - offers-gateway
  http:
  - match:
    - uri:
        exact: /offers
    route:
    - destination:
        host: offers
        port:
          number: 80
