openapi: 3.0.0
info:
  description: "This is a sample server offers Service.  You can find out more
    about     Swagger at [http://swagger.io](http://swagger.io) or on
    [irc.freenode.net, #swagger](http://swagger.io/irc/).      For this sample,
    you can use the api key `special-key` to test the
    authorization     filters."
  version: 1.0.1
  title: Retail API offers Service
  termsOfService: http://swagger.io/terms/
  contact:
    email: rajeshmi@google.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
tags:
  - name: Offers
    description: All offers 
paths:
  /offers:
    get:
      tags:
        - offers
      summary: Get All Offers
      description: ""
      operationId: getOffers
      responses:
        "200":
          description: OK (successfully authenticated)
        "405":
          description: Invalid input
        "403":
          description: Forbidden
      security:
        - api_key: []
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://api.offers.dynolab.app/
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: query
