apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: apik8s-gateway
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 443
      name: https
      protocol: HTTPS
    tls:
      mode: SIMPLE
      credentialName: apik8s-credential
    hosts:
    - "apik8s.dynolab.io"
