apiVersion: apigee.google.com/v1
kind: ApiProduct
metadata:
  name: retail-api-loyalty-product
  env : prod
  config: apigee-config-apigeex
  config-namespace: apigee-config
spec:
  # Add fields here
  apiResources:
  -  "/"
  name: retail-api-loyalty-product
  approvalType: auto
  description: Retail API Loyalty Product
  displayName: Retail API Loyalty Product
  attributes:
  - name: access
    value: public
  - name: apigee-remote-service-targets
    value: api.dynolab.app
  environments:
  - prod
  proxies:
  - remote-service
 # scopes: 
  #quota : "10"
  #quotaInterval : "1"
  #quotaTimeUnit : minute
