---
apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: apigee-config
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: apigee-config-apigeex
  namespace: apigee-config
data:
  mgmt_api: https://apigee.googleapis.com/v1
  service_account_secret : bap-amer-select-demo2-org-admin
  org_name: bap-amer-select-demo2
  env_name: default-dev
  profile: apigeex
  auth: token
